### PR TITLE
Close #3 and #4

### LINKED ISSUE #3: Generated tests always use FollowBtn
**Describe the bug**
The autogenerated `testing-library` test file always uses `FollowBtn` when you `getBy*`.

**To Reproduce**
1. `npx generate-react-cli component FancyComponent`
2. Open `FancyComponent.test.js`
3. See `const FollowBtn = ...`

**Expected behavior**
`const FollowBtn = getByText('FancyComponent Component');` should be `const FancyComponent = getByText('FancyComponent Component');`

### PR DESCRIPTION
**Pull request by ryanwalters**
Updates:
- Use camelCased component name for selecting component in `@testing-library` test file (#3)
- Use `getByTestId` vs `getByText` by default in `@testing-library` test file (#4)

### CODE REVIEW

File: src/templates/components/componentJsTemplate.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ import PropTypes from 'prop-types';
 import styles from './TemplateName.module.css';
 
 const TemplateName = () => (
-  <div className={styles.TemplateName}>
+  <div className={styles.TemplateName} data-testid="TemplateName">
```
Comment (arminbro) [inline src/templates/components/componentJsTemplate.js]: Not a huge deal but projects that use Enzyme as their test library will also get `data-testid="TemplateName"` that would not have any use.
